package quiz;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Grim
 */
//class for handling question data
public class Question {
    private String question;
    private int questionID;
    private Answer[] answers = new Answer[4]; // array of possible answers a b c d
    private int numAnswers = 0;

    public Question(String question ,int questionID ) throws SQLException {
        this.question = question;
        this.questionID = questionID;
        
        //table answers contains the 
        String SQL = "SELECT Answer, Correct FROM Answers WHERE QuestionFK="+ this.questionID;
        //AND correct_answer = true
        //table of data representing a database result set generated by the above sql statment
        //the managers method gets called and executed with the query and qsl statement 
        ResultSet result = Manager.getStMan().query(SQL); 
        
        //loops through the result set with the .next method
        while(result.next()){
            //returns the data fields from the db
            String answer = result.getString("Answer");
            boolean correct = result.getBoolean("Correct");
            //populates array with answers and passes 2 arguments 
            answers[numAnswers] = new Answer(answer , correct);
            //inc the numAnswers variable for each data field added
            numAnswers++;
        }
       
    }

    @Override
    public String toString() {
        String display = "";
        //letters link to the position of the question in the array
        String letters = "ABCD";
        //loop through answers array + use numAnswers as a val
        for (int i = 0; i < numAnswers; i++){
            //store data in display for displayed questions at array [i] index
            display += answers[i].toString(letters.charAt(i)) + "\n";
        }
        //returns question and possible answer
        return question + "\n\n" + display;
    }
  
    
    //checking if the answer is correct
    public boolean isCorrect(char letter){
        String letters = "ABCD";
        //checks answer options 1 by 1 
        int index = letters.indexOf(letter + "");
        // return correct answer to match from array by going through each one
        return answers[index].isCorrect();
    }
    
}
